# Toronto Maple Leafs 2024-25 season predictions

c("Auston Matthews wins the Hart Trophy",
  "Win the Presidents' Trophy",
  "Mitch Marner gets traded",
  "Craig Berube gets fired as Leafs' head coach",
  "Joseph Woll plays in at least 45 games",
  "Matthew Knies resigns for less than $4 million AAV",
  "John Tavares tests free agency at the end of the season",
  "Win the Stanley Cup",
  "Miss the playoffs",
  "Finish in the top 5% for PP",
  "Lose first game against the Canadiens",
  "Morgan Rielly misses less than 10 games due to injury",
  "Finish with a better points percentage at home than on the road",
  "Nicholas Robertson does not get traded",
  "Easton Cowan makes the team out of training camp",
  "Ryan Reaves fights in the home-opener against the Penguins",
  "Max Domi tops 50 points",
  "Bobby McMann records a hat-trick",
  "Anthony Stolarz finishes season with a save percentage above .910",
  "Endure a 5-game lossing streak before Christmas",
  "Loss a Game 7 in the playoffs",
  "Play Boston Bruins in the playoffs",
  "William Nylander records more than 100 points",
  "Craig Berube is a finalist for the Jack Adams Award")
